domain       = "Google-Cloud"
 disk_image   = "centos-cloud/centos-7-v20160119"
 disk_size    = "5"
 disk_type    = "pd-ssd"
 project      = "infrastructure-04"
 machine_type = "n1-standard-2"
 net          = "jenkins-net"
 name         = "gce-eu-west1d"